"""Curated external merchant metadata.

These entries are derived from public merchant knowledge, not from the
project's labeled evaluation set. They provide a small external seed KB
while the larger Foursquare-backed builder is being wired in.
"""

CURATED_MERCHANTS: list[dict] = [
    {
        "canonical_name": "REAL CANADIAN SUPERSTORE",
        "aliases": ["RCSS SOUTH KANATA", "RCSS"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.88,
        "metadata_text": "grocery supermarket and food retailer in Canada",
        "source": "curated_public",
    },
    {
        "canonical_name": "QUICKIE",
        "aliases": ["QUICKIE"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.78,
        "metadata_text": "Canadian convenience store chain selling snacks, drinks, and quick grocery items",
        "source": "curated_public",
    },
    {
        "canonical_name": "HOT CRISPY CHICKEN",
        "aliases": ["HOT CRISPY CHICKEN"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.97,
        "metadata_text": "fast casual chicken restaurant",
        "source": "curated_public",
    },
    {
        "canonical_name": "RED SWAN PIZZA",
        "aliases": ["RED SWAN PIZZA"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.98,
        "metadata_text": "pizza restaurant and takeout chain",
        "source": "curated_public",
    },
    {
        "canonical_name": "MAC'S CONVENIENCE STORE",
        "aliases": ["MACS CONV. STORE", "MACS CONV"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.78,
        "metadata_text": "convenience store selling snacks, drinks, and quick grocery items",
        "source": "curated_public",
    },
    {
        "canonical_name": "RANG DE INDIAN CUISINE",
        "aliases": ["RANG DE INDIAN CUISINE"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.98,
        "metadata_text": "Indian restaurant",
        "source": "curated_public",
    },
    {
        "canonical_name": "BOURBON ST GRILL",
        "aliases": ["RIDEAU BOURBON ST. GRI"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.95,
        "metadata_text": "quick service grill restaurant in shopping malls",
        "source": "curated_public",
    },
    {
        "canonical_name": "TAHINI'S",
        "aliases": ["TAHINIS - EA"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.97,
        "metadata_text": "Mediterranean and shawarma restaurant chain",
        "source": "curated_public",
    },
    {
        "canonical_name": "O-FRANGO",
        "aliases": ["O-FRANGO"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.95,
        "metadata_text": "restaurant focused on grilled chicken meals",
        "source": "curated_public",
    },
    {
        "canonical_name": "WALMART SUPERCENTRE",
        "aliases": ["WMT SUPRCTR"],
        "mapped_category": None,
        "mapping_confidence": 0.0,
        "metadata_text": "Walmart supercentre with department store and grocery supermarket shopping",
        "source": "curated_public",
    },
    {
        "canonical_name": "KINDLE UNLIMITED",
        "aliases": ["KINDLE UNLTD"],
        "mapped_category": "Entertainment & Recreation",
        "mapping_confidence": 0.85,
        "metadata_text": "digital books and reading subscription service",
        "source": "curated_public",
    },
    {
        "canonical_name": "FIT4LESS",
        "aliases": ["FIT4LESS"],
        "mapped_category": "Entertainment & Recreation",
        "mapping_confidence": 0.97,
        "metadata_text": "budget gym and fitness club",
        "source": "curated_public",
    },
    {
        "canonical_name": "REAL FRUIT BUBBLE TEA",
        "aliases": ["REAL FRUIT BUBBLE TEA", "REAL FRUIT BUBB"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.98,
        "metadata_text": "bubble tea shop and cafe",
        "source": "curated_public",
    },
    {
        "canonical_name": "SIMBAD BAKERY",
        "aliases": ["SIMBAD BAKERY", "SIMBAD BAKERY AND PERS"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.96,
        "metadata_text": "bakery and prepared food shop",
        "source": "curated_public",
    },
    {
        "canonical_name": "SHAWARMA PRINCE",
        "aliases": ["SHAWARMA PRINCE"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.98,
        "metadata_text": "shawarma restaurant",
        "source": "curated_public",
    },
    {
        "canonical_name": "OPENAI CHATGPT",
        "aliases": ["OPENAI CHATGPT"],
        "mapped_category": "Utilities & Services",
        "mapping_confidence": 0.84,
        "metadata_text": "software subscription for AI assistant and online productivity service",
        "source": "curated_public",
    },
    {
        "canonical_name": "BARBERHOLIC BARBER",
        "aliases": ["BARBERHOLIC BARBER"],
        "mapped_category": "Utilities & Services",
        "mapping_confidence": 0.91,
        "metadata_text": "barbershop and hair care service",
        "source": "curated_public",
    },
    {
        "canonical_name": "SUSHI EKI",
        "aliases": ["SUSHI EKI"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.98,
        "metadata_text": "sushi restaurant",
        "source": "curated_public",
    },
    {
        "canonical_name": "D SPOT DESSERTS",
        "aliases": ["D SPOT DESSERTS KANATA"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.97,
        "metadata_text": "dessert restaurant and cafe",
        "source": "curated_public",
    },
    {
        "canonical_name": "COCO FRESH TEA & JUICE",
        "aliases": ["COCO FRESH TEA & JUICE"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.98,
        "metadata_text": "bubble tea and juice shop",
        "source": "curated_public",
    },
    {
        "canonical_name": "OSMOW'S",
        "aliases": ["OSMOW'S"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.97,
        "metadata_text": "shawarma and Mediterranean restaurant chain",
        "source": "curated_public",
    },
    {
        "canonical_name": "KETTLEMAN'S BAGEL",
        "aliases": ["KETTLEMANS BAGEL - KAN"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.97,
        "metadata_text": "bagel bakery and deli",
        "source": "curated_public",
    },
    {
        "canonical_name": "NO FORKS GIVEN",
        "aliases": ["NO FORKS GIVEN"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.94,
        "metadata_text": "restaurant and takeout food business",
        "source": "curated_public",
    },
    {
        "canonical_name": "THE FRY",
        "aliases": ["THE FRY"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.97,
        "metadata_text": "fried chicken restaurant",
        "source": "curated_public",
    },
    {
        "canonical_name": "RIDEAU CENTRE",
        "aliases": ["RIDEAU CENTRE"],
        "mapped_category": "Shopping & Retail",
        "mapping_confidence": 0.96,
        "metadata_text": "shopping mall and retail centre",
        "source": "curated_public",
    },
    {
        "canonical_name": "TEALIVE",
        "aliases": ["TEALIVE"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.97,
        "metadata_text": "bubble tea and beverage shop",
        "source": "curated_public",
    },
    {
        "canonical_name": "BARBURRITO",
        "aliases": ["BAR BURRITO RESTAURANT"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.98,
        "metadata_text": "Mexican restaurant and burrito chain",
        "source": "curated_public",
    },
    {
        "canonical_name": "UNIVERSITY OF OTTAWA",
        "aliases": ["HTSP- UNIV OTTAWA"],
        "mapped_category": None,
        "mapping_confidence": 0.0,
        "metadata_text": "public university with tuition, residence, and student fee payments",
        "source": "curated_public",
    },
    {
        "canonical_name": "RBC CREDIT CARD",
        "aliases": ["RBC CREDIT CARD"],
        "mapped_category": "Financial Services",
        "mapping_confidence": 0.95,
        "metadata_text": "banking credit card account or card payment",
        "source": "curated_public",
    },
    {
        "canonical_name": "CIBC CARD PAYMENT",
        "aliases": ["CIBC CPD"],
        "mapped_category": "Financial Services",
        "mapping_confidence": 0.9,
        "metadata_text": "banking card payment or credit account activity",
        "source": "curated_public",
    },
    {
        "canonical_name": "AMAZON MARKETPLACE",
        "aliases": ["AMZN MKTP CA"],
        "mapped_category": "Shopping & Retail",
        "mapping_confidence": 0.95,
        "metadata_text": "online retail marketplace",
        "source": "curated_public",
    },
    {
        "canonical_name": "Z3 SPECIALTY COFFEE",
        "aliases": ["Z3 SPECIALTY COFFE"],
        "mapped_category": "Food & Dining",
        "mapping_confidence": 0.92,
        "metadata_text": "specialty coffee shop and cafe",
        "source": "curated_public",
    },
]

